apiVersion: batch/v1
kind: Job
metadata:
  name: job-test
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  template:
    metadata:
      labels:
        job-name: job-test
    spec:
      containers:
        - name: job-test
          image: perl:5.32.0
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
  